services:

  traefik:
    image: traefik:v3.0
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - core

  capacitor:
    image: fluxcd/flux2:v2.1.2
    command:
      - flux
      - ui
      - --address=0.0.0.0:9000
    networks:
      - core
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.capacitor.rule=Host(`capacitor.local`)"
      - "traefik.http.routers.capacitor.entrypoints=web"
      - "traefik.http.services.capacitor.loadbalancer.server.port=9000"

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_APP_MODE=development
    networks:
      - core
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana

  prometheus:
    image: prom/prometheus:v2.51.1
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    volumes:
      - prometheus:/prometheus
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    configs:
      - source: prometheus
        target: /etc/prometheus/prometheus.yml
    networks:
      - core
    ports:
      - 9090:9090

  fronius-exporter:
    build:
      context: .
    environment:
      - DEFAULT_NETWORK=192.168.1.0/24
      - RUST_LOG=debug
    networks:
      - core
    ports:
      - 8000:8000

volumes:
  grafana:
  prometheus:

networks:
  core:

configs:
  prometheus:
    file: ./config/prometheus.yml
