{
 "title": "⚡Power",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "🔋 Battery Charge",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fronius_bat_value{name=\"lefty\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🏠 House Draw",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fronius_power_gen{name=\"righty\"}) - sum(fronius_power_load{name=\"lefty\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🌞 PV Solar Gen",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fronius_power_pv", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Power Grid Draw",
   "type": "stat",
   "description": "Total Net Draw",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(fronius_power_grid)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "timeseries",
   "description": "The percentage of power left in the battery",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "fronius_bat_value", "legendFormat": "__auto" }
   ]
  },
  { "title": "Events", "type": "alertlist", "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 } },
  {
   "title": "Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "-fronius_power_load{name=\"lefty\"} ",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "fronius_power_gen{name=\"righty\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(fronius_power_gen{name=\"righty\"}) - sum(fronius_power_load{name=\"lefty\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grid and Battery Draw",
   "type": "timeseries",
   "description": "Positive Grid = Pulling from grid\nPositive Battery = Pulling from battery",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "fronius_power_grid", "legendFormat": "__auto" },
    { "expr": "fronius_power_akku", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Generation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expr": "sum(fronius_power_pv)", "legendFormat": "__auto" },
    { "expr": "fronius_power_akku", "legendFormat": "__auto" },
    { "expr": "fronius_power_grid", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Panel Generation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "fronius_power_pv", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Autonomy",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "fronius_self_consumption", "legendFormat": "__auto" },
    { "expr": "fronius_autonomy", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "🌡️ Temps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "fronius_temp_bat_ambient", "legendFormat": "__auto" },
    { "expr": "fronius_temp_bat_cell", "legendFormat": "__auto" },
    { "expr": "fronius_temp_inverter", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Grid Daily Transfer",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "last_over_time(sum(increase(fronius_power_grid[24h]))[1d:1d]) / (15 * 24)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🔋 Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fronius_bat_value", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "❤️ Battery Health",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fronius_bat_health", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "History Totals",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fronius_bat_energy_charged", "legendFormat": "__auto" },
    { "expr": "fronius_bat_energy_discharged", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Testing Reactive/Apparent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "targets": [
    { "expr": "fronius_power_reactive", "legendFormat": "__auto" },
    { "expr": "fronius_power_apparent", "legendFormat": "__auto" }
   ]
  }
 ]
}