name: Build and Publish Helm Chart

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Lint Helm chart
        run: helm lint charts/

      - name: Update Helm chart version
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          sed -i "s/^version:.*/version: ${VERSION}/" charts/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: ${VERSION}/" charts/Chart.yaml

      - name: Set chart version for non-tagged builds
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: |
          sed -i "s/^version:.*/version: latest/" charts/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: latest/" charts/Chart.yaml

      - name: Package Helm chart
        run: |
          mkdir -p .cr-release-packages
          helm package charts --destination .cr-release-packages
      
      - name: Upload Helm chart to GHCR
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io/${{ github.repository_owner }} --username ${{ github.actor }} --password-stdin
          helm push .cr-release-packages/*.tgz oci://ghcr.io/${{ github.repository_owner }}/charts
